### ISSUE TITLE
Utilisation de votre convertisseur de bibliothèques

### ISSUE THREAD

**Issue by EricPERONNIN** [laurentc2/LTspice2Kicad#2]
Bonjour,
je réalise actuellement une interface KiCad vers LTspice pour que la saisie de schéma se fasse totalement sous KiCad et la simulation sous LTspice. Mon interface permet de configurer la simulation .ac, .tran, ..., Monte Carlo, Worst Case ...
J'ai réalisé un convertisseur pour les composants standards (.ind, .cap, .bead) et comme j'ai vu votre convertisseur (que j'ai modifié pour "détecter" les fichiers utf-16le et le rendre compatible avec KiCad 5), je souhaiterai intégrer cette version modifiée à mon dépôt à venir.
M'y autorisez-vous ?
Cordialement,
Eric PERONNIN

**Comment by laurentc2** [comment]
Oui, bien sûr !  bientôt disponible sur Github ?
